### ISSUE TITLE
Segfault in helm-wrapper

### ISSUE THREAD

**Issue by alexanderjohn** [little-angry-clouds/kubernetes-binaries-managers#29]
I followed the manual installation instructions and was able to install `3.7.1` and `2.16.1`

When I run `helm`, 
Incorrect helm commands execute with no issue:
```
$ helm blahblah
Error: unknown command "blahblah" for "helm"
Run 'helm --help' for usage.
```

However, every 'successful' command ends with the following:

```
$ helm
The Kubernetes package manager
# ...
# ...
# ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4aad4f]

goroutine 1 [running]:
github.com/little-angry-clouds/kubernetes-binaries-managers/internal/wrapper.Wrapper(0x4e810e, 0x4)
	/home/runner/work/kubernetes-binaries-managers/kubernetes-binaries-managers/internal/wrapper/main.go:43 +0x4df
main.main()
	/home/runner/work/kubernetes-binaries-managers/kubernetes-binaries-managers/cmd/helm-wrapper/main.go:10 +0x36
```

**Comment by alexppg** [comment]
Hi, I'm gonna close this, if you still have this issue, feel free to reopen it.

**Comment by alexppg** [comment]
Sorry too hear it. Could

**Comment by alexppg** [comment]
If `helmenv` doesn't have the `version` parameter, it should mean that you're not using the latest version. Could you please upgrade?

**Comment by alexppg** [comment]
Awesome. I'll close this issue when I update the README.

**Comment by alexppg** [comment]
Done.
